services:
    _defaults:
        autoconfigure: true
        autowire: true

    VillaBrocante\GoogleShoppingFeed\Service\Feed:
        arguments:
            - '%contao.web_dir%'

    VillaBrocante\GoogleShoppingFeed\Cron\CreateFeed:
        tags:
            -
                name: contao.cronjob
                interval: "0 */12 * * *"
